    name: Python application CI/CD Saad Ahmad
    on:
      push:
        branches: [ "main" ] 
      pull_request:
        branches: [ "main" ]
        
    jobs:
      build:
        runs-on: ubuntu-latest 
        steps:
          - name: Checkout Repository 
            uses: actions/checkout@v2
          - name: Build Docker Image 
            run: |
              docker login -u ${{secrets. DOCKER_USERNAME}} -p S{{secrets. DOCKER_PASSWORD}} 
              docker build -t saadbangashh/1200426-pythonflask
          - name: Push Docker Image
            run: docker push saadbangashh/1200426-pythonflask
